package it.unina.control;

import it.unina.dto.OrderItemDTO;
import org.junit.jupiter.api.*;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

public class GestioneOrdiniControllerTest {

    private static final String URL = "jdbc:h2:file:./db/testdb;DB_CLOSE_DELAY=-1";
    private GestioneOrdiniController controller;

    @BeforeEach
    void setup() throws Exception {
        controller = new GestioneOrdiniController(URL, "sa", "");

        try (Connection c = DriverManager.getConnection(URL, "sa", "");
             Statement st = c.createStatement()) {

            // reset schema - drop dependent tables first to avoid foreign key constraint violations
            st.execute("DROP TABLE IF EXISTS consegna");
            st.execute("DROP TABLE IF EXISTS pagamento");
            st.execute("DROP TABLE IF EXISTS riga_ordine");
            st.execute("DROP TABLE IF EXISTS ordine");
            st.execute("DROP TABLE IF EXISTS panino");
            st.execute("DROP TABLE IF EXISTS carta_credito");
            st.execute("DROP TABLE IF EXISTS rider");
            st.execute("DROP TABLE IF EXISTS panineria");
            st.execute("DROP TABLE IF EXISTS cliente");



            st.execute("CREATE TABLE cliente (id_cliente BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, nome VARCHAR(60) NOT NULL, cognome VARCHAR(60) NOT NULL, indirizzo VARCHAR(200) NOT NULL, cap VARCHAR(10) NOT NULL, telefono VARCHAR(30) NOT NULL, email VARCHAR(120) NOT NULL)");
            st.execute("CREATE TABLE panineria (id_panineria BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, nome VARCHAR(120) NOT NULL, indirizzo VARCHAR(200) NOT NULL, cap VARCHAR(10) NOT NULL, telefono VARCHAR(30) NOT NULL, email VARCHAR(120) NOT NULL, iban VARCHAR(34) NOT NULL, nome_gestore VARCHAR(60) NOT NULL, cognome_gestore VARCHAR(60) NOT NULL)");
            st.execute("CREATE TABLE panino (id_panino BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id_panineria BIGINT NOT NULL, nome VARCHAR(120) NOT NULL, descrizione VARCHAR(400), prezzo DECIMAL(10,2) NOT NULL, disponibile BOOLEAN NOT NULL DEFAULT TRUE, CONSTRAINT fk_panino_panineria FOREIGN KEY (id_panineria) REFERENCES panineria(id_panineria))");
            st.execute("CREATE TABLE ordine (id_ordine BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id_cliente BIGINT NOT NULL, id_panineria BIGINT NOT NULL, ts_creazione TIMESTAMP NOT NULL, stato VARCHAR(20) NOT NULL, totale DECIMAL(10,2) NOT NULL DEFAULT 0.00, CONSTRAINT fk_ordine_cliente FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente), CONSTRAINT fk_ordine_panineria FOREIGN KEY (id_panineria) REFERENCES panineria(id_panineria))");
            st.execute("CREATE TABLE riga_ordine (id_ordine BIGINT NOT NULL, id_panino BIGINT NOT NULL, qta INT NOT NULL, prezzo_unit DECIMAL(10,2) NOT NULL, PRIMARY KEY (id_ordine, id_panino), CONSTRAINT fk_riga_ordine FOREIGN KEY (id_ordine) REFERENCES ordine(id_ordine) ON DELETE CASCADE, CONSTRAINT fk_riga_panino FOREIGN KEY (id_panino) REFERENCES panino(id_panino))");
            st.execute("CREATE TABLE rider (id_rider BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, nome VARCHAR(60) NOT NULL, cognome VARCHAR(60) NOT NULL, telefono VARCHAR(30) NOT NULL)");

            st.execute("CREATE TABLE carta_credito (id_carta BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id_cliente BIGINT NOT NULL UNIQUE, numero_carta VARCHAR(19) NOT NULL, scadenza VARCHAR(5) NOT NULL, intestatario VARCHAR(100) NOT NULL, CONSTRAINT fk_cc_cliente FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente))");

            st.execute("CREATE TABLE pagamento (" +
                    "id_pagamento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                    "id_ordine BIGINT NOT NULL," +
                    "metodo VARCHAR(20) NOT NULL," +
                    "esito VARCHAR(20) NOT NULL," +
                    "importo DECIMAL(10,2) NOT NULL," +
                    "ts TIMESTAMP NOT NULL," +
                    "auth_code VARCHAR(100)," +
                    "messaggio VARCHAR(500)," +
                    "CONSTRAINT fk_pagamento_ordine FOREIGN KEY (id_ordine) REFERENCES ordine(id_ordine) ON DELETE CASCADE" +
                    ")");

            st.execute("CREATE TABLE consegna (" +
                    "id_consegna BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                    "id_ordine BIGINT NOT NULL UNIQUE," +
                    "id_rider BIGINT NOT NULL," +
                    "ts_invio TIMESTAMP NOT NULL," +
                    "ts_consegna TIMESTAMP," +
                    "CONSTRAINT fk_consegna_ordine FOREIGN KEY (id_ordine) REFERENCES ordine(id_ordine) ON DELETE CASCADE," +
                    "CONSTRAINT fk_consegna_rider FOREIGN KEY (id_rider) REFERENCES rider(id_rider)" +
                    ")");

            // dati minimi
            st.execute("INSERT INTO cliente (nome,cognome,indirizzo,cap,telefono,email) VALUES ('A','B','Via X','80100','333','a@a.it')");
            st.execute("INSERT INTO panineria (nome,indirizzo,cap,telefono,email,iban,nome_gestore,cognome_gestore) VALUES ('P1','Via Y','80100','111','p@p.it','IT00','G','H')");
            st.execute("INSERT INTO panineria (nome,indirizzo,cap,telefono,email,iban,nome_gestore,cognome_gestore) VALUES ('P2','Via Z','80100','222','p2@p.it','IT00','G2','H2')");
            st.execute("INSERT INTO panino (id_panineria,nome,descrizione,prezzo,disponibile) VALUES (1,'Pan1','',6.50,TRUE)");
            st.execute("INSERT INTO panino (id_panineria,nome,descrizione,prezzo,disponibile) VALUES (2,'Pan2','',7.00,TRUE)");
            st.execute("INSERT INTO rider (nome,cognome,telefono) VALUES ('Paolo','Neri','333')");

        }
    }

    @Test
    void effettuaOrdine_OK() throws Exception {
        long id = controller.effettuaOrdine(1, 1, List.of(new OrderItemDTO(1, 2)));
        assertTrue(id > 0);
    }

    @Test
    void effettuaOrdine_ItemsVuota() {
        assertThrows(IllegalArgumentException.class,
                () -> controller.effettuaOrdine(1, 1, List.of()));
    }

    @Test
    void effettuaOrdine_QuantitaNonValida() {
        assertThrows(IllegalArgumentException.class,
                () -> controller.effettuaOrdine(1, 1, List.of(new OrderItemDTO(1, 0))));
    }

    @Test
    void effettuaOrdine_ClienteInesistente() {
        assertThrows(IllegalArgumentException.class,
                () -> controller.effettuaOrdine(999, 1, List.of(new OrderItemDTO(1, 1))));
    }

    @Test
    void effettuaOrdine_PaninoNonAppartiene() {
        // Pan2 appartiene a panineria 2, ma ordino su panineria 1
        assertThrows(IllegalArgumentException.class,
                () -> controller.effettuaOrdine(1, 1, List.of(new OrderItemDTO(2, 1))));
    }

    @Test
    void assegnaRider_OK() throws Exception {
        long idOrdine = controller.effettuaOrdine(1, 1, List.of(new OrderItemDTO(1, 1)));
        long idConsegna = controller.assegnaRider(idOrdine, 1);
        assertTrue(idConsegna > 0);
    }

    @Test
    void assegnaRider_RiderInesistente() throws Exception {
        long idOrdine = controller.effettuaOrdine(1, 1, List.of(new OrderItemDTO(1, 1)));
        assertThrows(IllegalArgumentException.class,
                () -> controller.assegnaRider(idOrdine, 999));
    }

    @Test
    void confermaConsegna_OK() throws Exception {
        long idOrdine = controller.effettuaOrdine(1, 1, List.of(new OrderItemDTO(1, 1)));
        controller.assegnaRider(idOrdine, 1);
        assertDoesNotThrow(() -> controller.confermaConsegna(idOrdine));
    }

}
